### PR TITLE
Check package.json for 'less' property

### PR DESCRIPTION
**Pull request by techwraith**
In order to allow for packages that have both less and css in them (like twitter-bootstrap), I thought it would be a good idea to default to checking a `less` property on package.json before checking for a style property.

This would allow module authors to distribute both a compiled css file and a less file, and have it work with `npm-css`, `rework-npm`, and `npm-less`.

### CODE REVIEW

**Comment by Raynos** [comment]
BOOM. good idea

**Comment by Raynos** [comment]
v0.3.2

**Comment by techwraith** [comment]
Sweet, thanks!

**Comment by ghost** [comment]
crazy related idea: a way of specifying arbitrary preprocessing transforms for css, similar to the browserify transform field

**Comment by techwraith** [comment]
@substack We're working on building that into `atomify-css` actually! Any
input would be appreciated.

**Comment by Raynos** [comment]
@substack why bother when you can `prepublish` a css file.

The only reason I have this is because I punched Less itself in the face to require other less files. i.e. I'm requiring less mixins which is the less version of functions.

There is no point in pre processing this to CSS because i'm trying to require a function not a blob of CSS.

**Comment by techwraith** [comment]
But some projects will want to use modules that have Less styles alongside plain css modules, stylus modules, and whatever else preprocessors module authors would like to use. I want an easy way to use _whatever_ module I want to use from npm, regardless of the needed preprocessor.

**Comment by techwraith** [comment]
@bclinkinbeard and I were talking about this here: https://github.com/Techwraith/atomify-css/pull/9 I may open up another issue to discuss this in the `atomify-css` repo.

**Comment by Raynos** [comment]
@Techwraith that's easy, prepublish css to npm if you plan to expose css. If you publish stylus to npm when you meant to publish CSS then dont do that and fix that module to publish css.

**Comment by bclinkinbeard** [comment]
The intention is more about allowing someone whose project/module uses CSS to use someone else's module that uses LESS (or Stylus, or whatever). Or vice versa. Devising a way to support arbitrary transforms of styles and treating LESS compilation as just one type of that would be awesome, and like @Techwraith said, something we've (briefly) discussed.

Right now, the biggest hurdle is the fact that Rework expects its plugins to be synchronous, and the LESS compiler is async. Rework seems [open to adding async support](https://github.com/reworkcss/rework/issues/2) if it can be done with a clean API, but that doesn't seem like a small undertaking.

The prepublish approach is probably a decent stopgap for now though, and I think transforms have value outside of mixing CSS and LESS.

**Pull request merged**
