### PR TITLE
always check for files before trying to import a module

### PR DESCRIPTION
**Pull request by spacepluk**
Hi there, this allows to import bootstrap's less files directly like this:

```
@import 'bootstrap/less/bootstrap.less';
```

Without the patch it fails to find [these](https://github.com/twbs/bootstrap/blob/master/less/mixins.less).

### CODE REVIEW

**Comment by Raynos** [comment]
it saddens me to see `mixins/foo` instead of `./mixins/foo`. That type of unambigiouty is really terrible.

Can we not just fix bootstrap to use `./mixins/foo` instead ?

**Comment by spacepluk** [comment]
I haven't tried to send them a PR... why is it so bad?

**Comment by bclinkinbeard** [comment]
@spacepluk In the Node ecosystem/resolution algorithm, starting paths with a `.` is the standard way to indicate a relative path, while the absence of a dot is interpreted to mean a named dependency, a la `node_modules`. I think we should submit a PR to Bootstrap, though it's possible they will reject it. Is `mixins.less` the only place this is done, or are there others?

**Comment by spacepluk** [comment]
Oh ok, I was thinking about it from a less-centric point of view.  I suppose there is a big percentage of less users that don't care about node conventions :(

Anyways, I'm going to double-check to see if there are more and I'm sending a PR to the bootstrap guys to see what happens.

**Comment by spacepluk** [comment]
https://github.com/twbs/bootstrap/pull/14266

**Comment by Raynos** [comment]
I would have to double check that LESS natively supports the `./mixins/foo` syntax, I'm not sure if it does.

If twitter doesn't want to change upstream we can just fix it here instead.

**Comment by spacepluk** [comment]
cool :)

**Comment by spacepluk** [comment]
It doesn't seem like the bootstrap guys want to merge the patch :(

**Comment by Raynos** [comment]
@spacepluk this PR looks good to me. #shipit

**Comment by Raynos** [comment]
Published v1.0.0

**Pull request merged**
